analyzer:
  exclude:
    - lib/generated_plugin_registrant.dart
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
  errors:
    inference_failure_on_function_invocation: ignore
    invalid_annotation_target: ignore
    no_runtimetype_tostring: ignore
    strict_raw_type: ignore
    
linter:
  rules:
    public_member_api_docs: false
