name: fluttercon_2024
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  http: ^1.2.1
  get_it: ^7.7.0
  injectable: ^2.4.2
  intl: ^0.18.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.3
  styled_widget: ^0.4.1
  textstyle_extensions: ^2.0.0-nullsafety
  equatable: ^2.0.5
  stream_transform: ^2.1.0
  bloc_concurrency: ^0.2.5

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  injectable_generator: ^2.1.6
  json_serializable: ^6.7.0 
  mockito: ^5.0.15

flutter:
  generate: true
  uses-material-design: true
